### PR TITLE
Docs initial revision

### LINKED ISSUE #6: [TODO] Make documentation
Use Sphinx to make some documentation for this.

### PR DESCRIPTION
**Pull request by shoshta73**
**Not** to be merged while **WIP** is in the **title**

Im Opening this PR for review, so there can be changes made as needed.

Should be able to close #6

### CODE REVIEW

**Comment by shoshta73** [comment]
Added installation istructions, docs for helpers and json-maestro module and cli tool documentation

**Comment by shoshta73** [comment]
Scripts are wrappers around mdbook commands so we dont have to store duplicate files

**Comment by shoshta73** [comment]
Removing WIP from title

**Comment by shoshta73** [comment]
This PR requires following changes to the repository:
- In Pages settings it requires `deploy from` options to be set to `from Action`

All currently shown examples have been tested locally, perhaphs there should be examples directory in the tests directory added later that would test if shown examples are working correctly

Current Examples are crude and are used more as place holders

**Comment by shoshta73** [comment]
Preview of docs site is avaible at https://shoshta73.github.io/json-maestro/

It is based of [this commit](https://github.com/gbowne1/json-maestro/pull/36/commits/4a2d02b0e2bcc6b1444479592c70e7d9757bfca8)

**Review by gbowne1 — APPROVED** [review]
- This change includes major documentation updates and uses mdbook which provides the developer and the user with adequate documentation to use this 

Approving this for merge.

**Review by gbowne1 — APPROVED** [review]
Approving License Shields.io badge update so that it doesn't show Not Found for merge

**Comment by shoshta73** [comment]
Merging as is.

Tagging merge commit as v0.0.2

**Pull request merged**
