### PR TITLE
feat: csv support for conversiont to json

### PR DESCRIPTION
**Pull request by shoshta73**
This is still work in progress,

requirements for this to be merged:
- [x] Converter app that will comunicate via stdin/stdout/stderr
- [x] Tests for new Loader and Converter classes
- [x] Update documentation
- [x] cleanup assertions in source code

### CODE REVIEW

**Comment by shoshta73** [comment]
@gbowne1 if you need/want anything else added to this pr feel please add it to the list in opening comment

**Comment by shoshta73** [comment]
@gbowne1 i didnt realize i was developing under windows virtaul machine, but i noticed long import times(under low resources in vm), so i made these 3 commits [fe4abfa](https://github.com/gbowne1/json-maestro/pull/48/commits/fe4abfa7b907b734c8bb240a4ca3919ce6fa390f), [39c3125](https://github.com/gbowne1/json-maestro/pull/48/commits/39c3125e3ba8effed2eb6e12d5a683d0f469f395), [31c6880](https://github.com/gbowne1/json-maestro/pull/48/commits/31c68806801d470d1f51743dd19da2ca0fbeaa5f)

**Comment by shoshta73** [comment]
requested since there were quite big changes

**Review by gbowne1 — APPROVED** [review]
I will have more time soon to both thoroughly test and review this more in depth but, at first glance visual review this looks like it will work just fine. I don't see anything in this WIP that stands out to be not great. Excellent work @shoshta73! Thanks. I have a bunch to contribute as soon as I'm able to, mainly enhancing the files we already have. I really appreciate your work.  Approving this set of WIP commits.

**Pull request merged**
