### PR TITLE
Fix unable to find config files

### PR DESCRIPTION
**Pull request by shoshta73**
Adds ability to use users shells native ability to autocomplete paths.

@gbowne1 are there any other improvements needed?

### CODE REVIEW

**Comment by shoshta73** [comment]
This Implements checking for provided files via cli, and if there are none it defaults to interactive mode.

-c / --clean - checks if it should remove comments
-s / --sort [a|d] - sorts, defaults to ascending mode

**Comment by shoshta73** [comment]
I would also suggest to merge this with squash and merge option

**Comment by gbowne1** [comment]
I can't think of any other improvments just yet.  There's a bunch of features I would like to add but they would depend on a few things.

**Review by gbowne1 — APPROVED** [review]
These changes include two tests and fixes to src/jsonmaestro 

They appear to work properly after some testing.

Approving this for merge and merging as is.

Thank you for your contributions. :+1:

**Comment by gbowne1** [comment]
Several of my systems don't have setuptools installed.. should that be included in requirements to make it easy for the user? 

I just initially added stuff that would be helpful in development for formatting, linting, etc.  in case the developer needed some tools they didnt have already.

**Comment by shoshta73** [comment]
Setuptools package can be included in setup.py. I personally dont put them in setup.py files becase it is pretty easy to install them and post od the pyton packages that can be run as "standalone" application are usually installed in some local virtual enviroment contained somewhere in user facing filesystem (like $HOME/venv) or via pipx.

I can add them into the setup.py its quick change and if recall correctly it doesnt affect the structure of installation other than venv itself.

**Comment by gbowne1** [comment]
no need if you don't think its necessary.. just was thinking of people with systems that didnt have this installed even though it would be simple to do the install themselves.

**Pull request merged**
