### PR TITLE
feat: logger utility

### PR DESCRIPTION
**Pull request by shoshta73**
Implements simple logging utility, with keyword/log level coloring.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- checked out this change locally for testing and review for merge

All tests passed

This added feature and code did not  seem to cause any additional errors or warnings.

Approving this change for merge

**Review by gbowne1 — APPROVED** [review]
Approving this PR for merge 

Checked out the updates locally and it seems to me after some testing here that it works as intended.

**Comment by shoshta73** [comment]
Final revision of logging utility adds fromat functions (logf, infof ...)

**Review by gbowne1 — APPROVED** [review]
- Checked out this logger utility feature locally for review and testing for merge

This appears to work fine.  I tested what I could so far.

Tests appear to pass.

Approving this for merge.

**Pull request merged**
