### PR TITLE
Cleanup tests

### LINKED ISSUE #26: [QAQC] test/test workflow / action fails
The test/test workflow/action fails on PR run

### PR DESCRIPTION
**Pull request by shoshta73**
Closes #26,

I am strongly reccomending to delay merging this PR until #22 is not resolved so we can frist move patch file 0001 to the source instead of keeping it in /patches directory

### CODE REVIEW

**Comment by gbowne1** [comment]
I should note.. my local venv failed.  VSCode tried to show me what to do about this.  I havent set up python tooling in Vi/Vim yet.. I'm slow right now.

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally for testing and review for merge.

This looks good.  This is a part of test cleanup. From what I am able to tell it works fine.

Approving for merge.

**Comment by shoshta73** [comment]
@gbowne1 waiting for review of PR #29 to avoid potential mess with workflows

**Comment by gbowne1** [comment]
Still testing and reviewing

**Pull request merged**
